### PR TITLE
feat(lib): add docstrings to S3 backend resource

### PR DESCRIPTION
**Pull request by aayushharwani-aidash**
Have added doc-string to s3 backend. 
Working on issue -[https://github.com/hashicorp/terraform-cdk/issues/1268]( https://github.com/hashicorp/terraform-cdk/issues/1268)

### CODE REVIEW

**Comment by aayushharwani-aidash** [comment]
> Hi @aayushharwani-aidash 👋 Thank you for the PR 👍 Looking good.
> 
> fyi: I adjusted the title of the PR to satisfy our linting rules for PRs.
> 
> Also, for PRs with a single commit, that rule also applies to the commit message, so you'd have to adjust it – or I can take care of that, if you want 😇

can you help me in doing it ?

**Comment by ansgarm** [comment]
> > Hi @aayushharwani-aidash 👋 Thank you for the PR 👍 Looking good.
> > fyi: I adjusted the title of the PR to satisfy our linting rules for PRs.
> > Also, for PRs with a single commit, that rule also applies to the commit message, so you'd have to adjust it – or I can take care of that, if you want 😇
> 
> can you help me in doing it ?

If you want to do it yourself and are using Git locally on the CLI, you can run:
```
git commit --amend
```
and then edit the message and afterwards run
```
git push --force
```
to push that changed commit to this PR.

If I should do that for you, just tell me. Happy to do that for you, if you want.

**Comment by aayushharwani-aidash** [comment]
> > > Hi @aayushharwani-aidash 👋 Thank you for the PR 👍 Looking good.
> > > fyi: I adjusted the title of the PR to satisfy our linting rules for PRs.
> > > Also, for PRs with a single commit, that rule also applies to the commit message, so you'd have to adjust it – or I can take care of that, if you want 😇
> > 
> > 
> > can you help me in doing it ?
> 
> If you want to do it yourself and are using Git locally on the CLI, you can run:
> 
> ```
> git commit --amend
> ```
> 
> and then edit the message and afterwards run
> 
> ```
> git push --force
> ```
> 
> to push that changed commit to this PR.
> 
> If I should do that for you, just tell me. Happy to do that for you, if you want.

Will give a try.

**Comment by aayushharwani-aidash** [comment]
@ansgarm  have made changes, as suggested by you

**Review by ansgarm — APPROVED** [review]

**Comment by ansgarm** [comment]
Thanks again for your contribution @aayushharwani-aidash 👍

**Pull request merged**
