### PR TITLE
chore: clean up unreleased sentry releases

### PR DESCRIPTION
**Pull request by DanielMSchmidt**

### CODE REVIEW

**Review by ansgarm — APPROVED** [review]
Nice 👏

If this works, we can remove/reword this section: https://github.com/hashicorp/terraform-cdk/blob/main/CONTRIBUTING.md?plain=1#L294

**Review by mutahhir — APPROVED** [review]

**Comment by mutahhir** [comment]
Just remembered: Will this revert the release if Homebrew fails? or was that fixed already?

**Comment by ansgarm** [comment]
Ah, good catch. I'd say it shouldn't revert it in that case 🙈

**Comment by DanielMSchmidt** [comment]
It was not fixed yet, I'm still working on getting the overall release out

**Comment by ansgarm** [comment]
> Maybe we should just move to a different mechanic for determening if sth has been released, e.g. the npm release

One benefit to using Sentry is that it can block further release workflows from starting. Using NPM will only "activate" the block when the release is done.

So we'd need to ensure that we (or Mergify 😅) don't merge anything while a release is running.

**Pull request closed without merging**
