### PR TITLE
fix(lib): expose `conditional`

### LINKED ISSUE #2818: Expose `conditional()` and other expression helpers through JSII
### Description

I want to use conditions  when trying to assign values  inside locals.
example : 
locals {
driver_node_type       = var.driver_node_type != null ? var.driver_node_type : var.instance_type
maybe_driver_node_type = var.driver_instance_pool_id != null ? null : local.driver_node_type
} 
and i didn't  find any documentation about this  topic, it is implemented or not  yet ? 

### Links

https://developer.hashicorp.com/terraform/cdktf/concepts/variables-and-outputs#local-values

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by BJMg**
### Related issue

Fixes #2818

### Description

Missing conditional expression in Java and other non-typescript languages. This PR attempts to expose it to JSII.

### Checklist

- [x] I have updated the PR title to match [CDKTF's style guide](https://github.com/hashicorp/terraform-cdk/blob/main/CONTRIBUTING.md#pull-requests-1)
- [x] I have run the linter on my code locally
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation if applicable
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works if applicable
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by BJMg** [comment]
> [CLA assistant check](https://cla.hashicorp.com/hashicorp/terraform-cdk?pullRequest=3264)
> 
> Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-cdk?pullRequest=3264)
> 
> [Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)
> 
> Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-cdk?pullRequest=3264).

This is False Positive I have signed the CLA even before I created PR. And it is signed when I open the link. Recheck doesn't help.

**Review by DanielMSchmidt — APPROVED** [review]
Awesome work, thanks for the help 🙌

**Comment by xiehan** [comment]
@BJMg We'd love to merge your PR, but we can't do so until the CLA has been confirmed to be signed!

If the CLA bot is saying the CLA hasn't been signed yet, it's most likely because the email address you signed it with (the default email address associated with your GitHub account) doesn't match the email address on the commit (in the git log). The email address on the commit is jimarek@cisco.com. You'll need to either re-sign the CLA using that email address, or do some sort of `git commit config --global user.email "your email"` and `git commit --amend` on the commit to use the email address that you signed the CLA with.

**Comment by BJMg** [comment]
> @BJMg We'd love to merge your PR, but we can't do so until the CLA has been confirmed to be signed!
> 
> If the CLA bot is saying the CLA hasn't been signed yet, it's most likely because the email address you signed it with (the default email address associated with your GitHub account) doesn't match the email address on the commit (in the git log). The email address on the commit is [jimarek@cisco.com](mailto:jimarek@cisco.com). You'll need to either re-sign the CLA using that email address, or do some sort of `git commit config --global user.email "your email"` and `git commit --amend` on the commit to use the email address that you signed the CLA with.

Thanks for clarification. I haven't realized it takes email from my commits. Everything should be fine now.

**Pull request merged**
