### PR TITLE
chore(docs): Add serverless application guide

### LINKED ISSUE #733: End-to-end serverless workflow
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
This is a draft! Let's talk before starting work on this.

The purpose of this project is to design a good end-to-end workflow for building and deploying serverless applications to popular cloud providers. This is simultaneously a documentation and design exercise. In the first iteration, the documentation should describe how to implement these workflows using CDK for Terraform as it exists today.

While writing that documentation, consider what else we could do to simplify the workflow and make it more idiomatic in each language and cloud provider. File enhancement requests, bugs, and link them back to this issue.

Use case: user wants to deploy a simple serverless application without having to stand up or operate other infrastructure.

#### Goals
* All resources are defined in a single codebase
* Examples available for AWS Lambda, Azure Functions, and (stretch goal) Google Cloud Functions
* Deploy functions, load balancers, security groups, storage buckets etc as needed - no manual setup outside of `cdktf deploy` should be needed.
* The serverless functions, as well as the CDK for Terraform code examples, should be implemented in TypeScript, Python, and Go

#### Stretch goals
As time permits, more advanced permutations would also be helpful, such as:
* deploying and configuring persistence (db, storage buckets) including setting up authentication to the persistence
* separately deploying a toy backend API and front-end as separate containers
* Provide a clear developer workflow for publishing to development/staging/production environments
* When the deploy completes, show (using an output?) the URL the web application is available at

#### Ideas for sample applications
In order to illustrate serverless use cases, we need some concrete use cases that are representative of common scenarios. Below, I've proposed some ideas. I'll leave it to whoever picks up this ticket to define the exact cases. Please pick one or two and add a more detailed definition (edit this issue as needed) prior to starting work.

* Simple REST endpoint that uses the cloud provider's key-value store for persistence
  * possibly accompanied by a simple statically hosted (cloud storage bucket) front-end app that pulls data from the endpoint, to show how both can be deployed as separate stacks
* Recurring (e.g. cron job) lambda that polls something and stores the result (probably in cloud provider's key-value store)
* Simple file processing pipeline where:
  * a file is POSTed to a first HTTP endpoint, which saves it to a cloud storage bucket
  * the upload event triggers another function, which compresses (gzip is fine) the file and deletes the original uncompressed file
  * a third HTTP endpoint shows a list of compressed files which are available for download
  * every day any compressed files over 24 hours old are deleted

Please feel free to suggest other toy use cases instead of these! This is intended as a prompt.

### Deliverables
The immediate practical output will be end-to-end documentation published in this GitHub. File any ideas you have for improving it as enhancement requests linked to this issue for ease of tracking.

### PR DESCRIPTION
**Pull request by ansgarm**
Adds a guide explaining the end to end serverless example.

[rendered version](https://github.com/hashicorp/terraform-cdk/blob/add-serverless-application-guide/docs/full-guide/serverless-application-typescript.md)
Repo with end to end serverless example: https://github.com/hashicorp/cdktf-integration-serverless-example (also linked in guide)

What do you think having this guide inside the newly created `docs/full-guide` directory? Happy to move it elsewhere if that seems off.

Resolves #733

### CODE REVIEW

**Comment by jsteinich** [comment]
Looks interesting. Some possible future changes to the example:

- Lock down the S3 bucket so that all requests need to go through CloudFront.
- Use the S3 bucket object resource instead of syncing
- Use [IAM Floyd](https://www.npmjs.com/package/iam-floyd) or similar to provide code first iam policies
- Call out that the different environments are different stack

**Comment by ansgarm** [comment]
Thank you for the great feedback, @jsteinich!

>  Lock down the S3 bucket so that all requests need to go through CloudFront.

We need to use the web hosting feature of the S3 bucket to serve the `index.html` for all unknown paths (due to the frontend being a single page application). I could not find a way to restrict the S3 bucket website hosting to only CloudFront and directly serving the files does not work for the application. Is there a way to achieve this that I overlooked?

> Use the S3 bucket object resource instead of syncing

I thought about that as well. However it didn't feel right. Currently the frontend has ~10ish files that are deployed to the S3 Bucket, however that number could grow substantially for a bigger application. This would result in the same number of (generated) S3 bucket object resources in Terraform.  
One alternative could be to build a custom resource / custom Terraform resource which takes care of the copying. As far as I know the AWS CDK bundles files in a zip and uses a Lambda that extracts the files into an S3 Bucket for a similar use case.


> Use [IAM Floyd](https://www.npmjs.com/package/iam-floyd) or similar to provide code first iam policies

Great idea. [Noted](https://github.com/hashicorp/cdktf-integration-serverless-example/commit/6b0fb158139ca50d26641cbe1cdc93c39314e77c).

>  Call out that the different environments are different stack

[Done](https://github.com/hashicorp/terraform-cdk/commit/f89dc8c6a9a2477fe25cda0f10ec498ff2420dc5).

**Comment by jsteinich** [comment]
> I thought about that as well. However it didn't feel right. Currently the frontend has ~10ish files that are deployed to the S3 Bucket,

Makes sense. For some reason I was thinking it was single file

**Comment by jsteinich** [comment]
> I could not find a way to restrict the S3 bucket website hosting to only CloudFront and directly serving the files does not work for the application. Is there a way to achieve this that I overlooked?

Here's some code that we have:
```c#
private VariableConditionResource<CloudfrontOriginAccessIdentity> ApplyBucketPolicy(S3Bucket bucket)
        {
            {//public
                var publicBucketPolicy = new PolicyDocument
                {
                    Statements = {new S3().ToGetObject().OnObject(Config.WebSiteDomain, "*").ForPublic()}
                };

                new VariableConditionResource<S3BucketPolicy>(!Config.UseCloudFront,
                    new S3BucketPolicy(this, "public_s3_policy", new S3BucketPolicyConfig
                    {
                        Bucket = bucket.Id,
                        Policy = publicBucketPolicy.ToJson()
                    }), true);
            }

            {//cloudfront
                new VariableConditionResource<S3BucketPublicAccessBlock>(Config.UseCloudFront,
                    new S3BucketPublicAccessBlock(this, "access_block", new S3BucketPublicAccessBlockConfig
                    {
                        Bucket = bucket.Id,
                        IgnorePublicAcls = true
                    }));

                var accessIdentity = new VariableConditionResource<CloudfrontOriginAccessIdentity>(Config.UseCloudFront,
                    new CloudfrontOriginAccessIdentity(this, "cf_access_identity", new CloudfrontOriginAccessIdentityConfig
                    {
                        Comment = "Access S3 bucket content only through CloudFront"
                    }));

                var cfBucketPolicy = new PolicyDocument
                {
                    Statements =
                    {
                        new S3().ToGetObject().OnObject(Config.WebSiteDomain, "*")
                            .For(accessIdentity.StringValue(nameof(accessIdentity.Resource.IamArn)))
                    }
                };
                
                new VariableConditionResource<S3BucketPolicy>(Config.UseCloudFront,
                    new S3BucketPolicy(this, "cf_s3_policy", new S3BucketPolicyConfig
                    {
                        Bucket = bucket.Id,
                        Policy = cfBucketPolicy.ToJson()
                    }));

                return accessIdentity;
            }
        }

//within cloud front distribution
Origin = new ICloudfrontDistributionOrigin[]
                {
                    new CloudfrontDistributionOrigin
                    {
                        DomainName = bucket.BucketDomainName,
                        OriginId = $"s3-origin-{bucket.Id}",
                        OriginPath = "",
                        
                        S3OriginConfig = new ICloudfrontDistributionOriginS3OriginConfig[]
                        {
                            new CloudfrontDistributionOriginS3OriginConfig
                            {
                                OriginAccessIdentity = cfAccessIdentity.StringValue(nameof(cfAccessIdentity.Resource.CloudfrontAccessIdentityPath))
                            }
                        }
                    }
                },
```

**Comment by ansgarm** [comment]
Thanks @jsteinich!
[Added it](https://github.com/hashicorp/cdktf-integration-serverless-example/commit/195737c51d79fe253377ee24fd5288f4be163f3b) to the ideas for future iterations.

**Review by DanielMSchmidt — APPROVED** [review]
Quite a different style from my version, but I like it!

**Pull request merged**
