### PR TITLE
chore: Update Digital Team Files

### PR DESCRIPTION
**Pull request by hashibot-web**
# Description

Updates managed website-related files.

- `website/Makefile`
- `website/scripts/should-build.sh`
- `website/scripts/website-build.sh`
- `website/scripts/website-start.sh`

> **Note**
>
> This pull request was opened via the Digital team's automation. If you have questions, please tag @hashicorp/web-platform

### CODE REVIEW

**Comment by ansgarm** [comment]
@hashicorp/web-platform are these generated PRs expected to be reviewed manually or can they just be merged if CI passes? If yes, we could check whether we want introduce some `automerge` label and automation that would merge these PRs if CI is green 😁

**Comment by thiskevinwang** [comment]
> @hashicorp/web-platform are these generated PRs expected to be reviewed manually or can they just be merged if CI passes? If yes, we could check whether we want introduce some `automerge` label and automation that would merge these PRs if CI is green 😁

@ansgarm I think we still want to manually approve these, at least for the near future. And sometimes we push additional commits to these PRs

**Comment by ansgarm** [comment]
@thiskevinwang Alright! Thanks for clarifying 👍

**Review by thiskevinwang — APPROVED** [review]

**Comment by thiskevinwang** [comment]
👋 @hashicorp/cdktf, requesting a merge on this if it looks good!

**Pull request merged**
