### PR TITLE
feat(cli): Automatically Update Locked Providers

### LINKED ISSUE #1863: Updating pre-built providers can result in "Failed to query available provider packages" error
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.10+
any language

### Affected Resource(s)

Pre-built providers

### Debug Output

```
40422  Initializing the backend...
40422  Initializing provider plugins...
       - Reusing previous version of hashicorp/azuread from the dependency lock file

⠸  Processing
[2022-06-11T16:43:10.133] [ERROR] default - ╷

│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/azuread: locked provider registry.terraform.io/hashicorp/azuread
│ 2.19.1 does not match configured version constraint 2.22.0; must use
│ terraform init -upgrade to allow selection of new versions
```

### Expected Behavior

Commands run successfully

### Actual Behavior

Above error as Terraform needs to reinitialize

### Steps to Reproduce

1. Create new cdktf typescript project
2. `npm install @cdktf/provider-azuread@0.4.7`
3. Add azuread provider to `main.ts`
4. `cdktf diff`
5. `npm install @cdktf/provider-azuread@0.5.17`
6. `cdktf diff`

### References

-https://discuss.hashicorp.com/t/error-failed-to-query-available-provider-packages-locked-provider/40422

### PR DESCRIPTION
**Pull request by jsteinich**
Fixes #1863

When [locked providers](https://www.terraform.io/language/files/dependency-lock) aren't compatible with currently specified providers, automatically update the locked version.
Users are likely to run into this situation when updating a pre-built provider package.

Still todo:
* Possibly exposing behavior as an option

### CODE REVIEW

**Comment by jsteinich** [comment]
I'm a bit torn on whether an update to disable the auto upgrade is needed. From a developer perspective it seems unnecessary as you already went through the effort to upgrade the provider package; hence signally a desire to upgrade. I can imagine some organization wanting even tighter control, but that could be contrived.
@ansgarm @DanielMSchmidt any thoughts?

**Comment by DanielMSchmidt** [comment]
I'm picking up work on the overarching `cdktf provider update` command (#1745), just so you know :)

**Comment by jsteinich** [comment]
I'm leaning more towards providing an option to disable the automatic lock file update. I think it makes sense as a value in `cdktf.json` rather than a cli option for every command; however, the current pattern would require passing the value through every command. Just reading `cdktf.json` at a later point could be viable. Could also just generally pass the contents through every command as a single argument.

**Review by ansgarm — APPROVED** [review]

**Review by DanielMSchmidt — APPROVED** [review]

**Comment by jin-ahn** [comment]
I don't believe this actually works

in my package.json I had
```
  "dependencies": {
    "@cdktf/provider-aws": "^9.0.0",
    "@cdktf/provider-null": "^2.0",
    "cdktf": "^0.12.0",
```

I upgraded my cdktf-cli to 14.3. I ran `npm uninstall cdktf`. Updated my package.json to have
```
  "dependencies": {
    "@cdktf/provider-aws": "^9.0.0",
    "@cdktf/provider-null": "^2.0",
    **"cdktf": "^0.14.3",**
```
Ran `npm i`

Now at this point I expect to be able to run `cdktf provider upgrade aws,null` and have it update my packages and my cdktf.json for me. But instead this breaks with
```
λ cdktf provider upgrade null
[2022-12-09T13:18:12.427] [ERROR] default - npm ERR! code ELSPROBLEMS

npm ERR! code ELSPROBLEMS
[2022-12-09T13:18:12.429] [ERROR] default - npm ERR! invalid: cdktf@0.14.3 /Users/jinahn/Development/anedot/cdktf/aws/ec2-stack/node_modules/cdktf
{
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "invalid: cdktf@0.14.3 /Users/jinahn/Development/anedot/cdktf/aws/ec2-stack/node_modules/cdktf",
    "detail": ""
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /$redacted/.npm/_logs/2022-12-09T21_18_12_286Z-debug-0.log

npm ERR! invalid: cdktf@0.14.3 `$redacted/cdktf/aws/ec2-stack/node_modules/cdktf
{
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "invalid: cdktf@0.14.3 $redacted/cdktf/aws/ec2-stack/node_modules/cdktf",
    "detail": ""
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /$redacted/.npm/_logs/2022-12-09T21_18_12_286Z-debug-0.log
Error: External Error: Could not determine CDKTF version. Please make sure you are in a directory containing a CDKTF project and have all dependencies installed.
    at Object.External (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:41856)
    at Object.ZFr (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:29211)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async qp.handleCommand (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:54:479)
    at async B.handler (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:29879)
Collecting Debug Information...
/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: External Error: Could not determine CDKTF version. Please make sure you are in a directory containing a CDKTF project and have all dependencies installed.
    at Object.External (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:41856)
    at Object.ZFr (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:29211)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async qp.handleCommand (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:54:479)
    at async B.handler (/opt/homebrew/Cellar/cdktf/0.14.3/libexec/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:29879) {
  __type: 'External'
}

Node.js v18.12.1
```

The only way to actually upgrade is to go in, npm uninstall all my providers. Go online to the npm repostory figure out which version of each provider is compatiable with the version of cdktf I am using and re-add them to my package.json. 

This is the most cumbersome way to upgrade in no way streamlined at all. Am I missing something?

**Comment by jsteinich** [comment]
@jin-ahn I copied your feedback to a new issue (#2437) so that it doesn't get lost.

**Pull request merged**
