### PR TITLE
chore(tests): parallelize tests

### PR DESCRIPTION
**Pull request by DanielMSchmidt**

### CODE REVIEW

**Comment by ansgarm** [comment]
Oh wow, it is surprising that it runs 🤔😄

**Comment by DanielMSchmidt** [comment]
Yeah me too, I just wanted to see the error :D I'll retrigger to make sure :)

**Comment by DanielMSchmidt** [comment]
Timechart first run

```
[    3.000s ] .                                                                                * main-3351545773
[ 1728.462s ] ├──────────────────────────────────────────────────────────────────────────────┤ * checkrun-timechart-3351545901
[  444.000s ] ├──────────────────┤                                                             * build (0.15.4, csharp)-3351545906
[  947.000s ] ├─────────────────────────────────────────┤                                      * build (0.15.4, java)-3351545906
[  502.000s ] ├─────────────────────┤                                                          * build (0.15.4, python)-3351545906
[ 1706.000s ] ├────────────────────────────────────────────────────────────────────────────┤   * build (0.15.4, go)-3351545906
[  348.000s ] ├─────────────┤                                                                  * build (0.14.11)-3351545907
[  351.000s ] ├──────────────┤                                                                 * build (0.15.4)-3351545907
[  710.000s ] ├──────────────────────────────┤                                                 * build (0.15.4, typescript)-3351545906
[  442.000s ]                  ├──────────────────┤                                            * linux_integration (0.15.4, java)-3351545907
[ 1130.000s ]                  ├─────────────────────────────────────────────────┤             * windows_integration (0.14.11, typescript)-3351545907
[  137.000s ]                  ├────┤                                                          * linux_integration (0.14.11, go)-3351545907
[  588.000s ]                  ├─────────────────────────┤                                     * windows_integration (0.15.4, csharp)-3351545907
[  779.000s ]                  ├─────────────────────────────────┤                             * linux_integration (0.14.11, python)-3351545907
[  297.000s ]                  ├───────────┤                                                   * windows_integration (0.14.11, go)-3351545907
[  146.000s ]                  ├────┤                                                          * linux_integration (0.15.4, go)-3351545907
[  658.000s ]                  ├────────────────────────────┤                                  * windows_integration (0.14.11, java)-3351545907
[  588.000s ]                  ├─────────────────────────┤                                     * windows_integration (0.14.11, csharp)-3351545907
[  786.000s ]                  ├──────────────────────────────────┤                            * linux_integration (0.15.4, python)-3351545907
[  461.000s ]                  ├───────────────────┤                                           * linux_integration (0.15.4, csharp)-3351545907
[  523.000s ]                  ├──────────────────────┤                                        * linux_integration (0.14.11, csharp)-3351545907
[  922.000s ]                  ├────────────────────────────────────────┤                      * linux_integration (0.14.11, typescript)-3351545907
[  812.000s ]                  ├───────────────────────────────────┤                           * linux_integration (0.15.4, typescript)-3351545907
[  499.000s ]                  ├────────────────────┤                                          * linux_integration (0.14.11, java)-3351545907
[ 1134.000s ]                  ├──────────────────────────────────────────────────┤            * windows_integration (0.15.4, typescript)-3351545907
[ 1124.000s ]                  ├─────────────────────────────────────────────────┤             * windows_integration (0.14.11, python)-3351545907
[  624.000s ]                  ├──────────────────────────┤                                    * windows_integration (0.15.4, java)-3351545907
[  274.000s ]                  ├──────────┤                                                    * windows_integration (0.15.4, go)-3351545907
[  988.000s ]                  ├───────────────────────────────────────────┤                   * windows_integration (0.15.4, python)-3351545907
```

**Comment by DanielMSchmidt** [comment]
Timechart second run

```
[    3.000s ] .                                                                                * main-3351986116
[ 1999.000s ] ├────────────────────────────────────────────────────────────────────────────┤   * build (0.15.4, go)-3351986338
[  282.000s ] ├─────────┤                                                                      * build (0.14.11)-3351986333
[  431.000s ] ├───────────────┤                                                                * build (0.15.4, csharp)-3351986338
[ 2012.042s ] ├──────────────────────────────────────────────────────────────────────────────┤ * checkrun-timechart-3351986335
[  464.000s ] ├────────────────┤                                                               * build (0.15.4, python)-3351986338
[  690.000s ] ├─────────────────────────┤                                                      * build (0.15.4, typescript)-3351986338
[  918.000s ] ├──────────────────────────────────┤                                             * build (0.15.4, java)-3351986338
[  263.000s ] ├────────┤                                                                       * build (0.15.4)-3351986333
[  515.000s ]             ├──────────────────┤                                                 * linux_integration (0.14.11, csharp)-3351986333
[  474.000s ]             ├────────────────┤                                                   * linux_integration (0.15.4, java)-3351986333
[  750.000s ]             ├───────────────────────────┤                                        * linux_integration (0.15.4, python)-3351986333
[  482.000s ]             ├─────────────────┤                                                  * linux_integration (0.14.11, java)-3351986333
[  773.000s ]             ├────────────────────────────┤                                       * linux_integration (0.15.4, typescript)-3351986333
[  143.000s ]             ├───┤                                                                * linux_integration (0.15.4, go)-3351986333
[  992.000s ]             ├─────────────────────────────────────┤                              * linux_integration (0.14.11, python)-3351986333
[  143.000s ]             ├───┤                                                                * linux_integration (0.14.11, go)-3351986333
[  711.000s ]             ├──────────────────────────┤                                         * windows_integration (0.14.11, csharp)-3351986333
[  652.000s ]             ├───────────────────────┤                                            * windows_integration (0.15.4, java)-3351986333
[ 1071.000s ]             ├────────────────────────────────────────┤                           * windows_integration (0.14.11, typescript)-3351986333
[  680.000s ]             ├────────────────────────┤                                           * windows_integration (0.14.11, java)-3351986333
[  618.000s ]             ├──────────────────────┤                                             * windows_integration (0.15.4, csharp)-3351986333
[  504.000s ]             ├─────────────────┤                                                  * linux_integration (0.15.4, csharp)-3351986333
[  312.000s ]             ├──────────┤                                                         * windows_integration (0.14.11, go)-3351986333
[ 1149.000s ]             ├───────────────────────────────────────────┤                        * windows_integration (0.15.4, python)-3351986333
[  293.000s ]             ├─────────┤                                                          * windows_integration (0.15.4, go)-3351986333
[ 1251.000s ]             ├───────────────────────────────────────────────┤                    * windows_integration (0.14.11, python)-3351986333
[ 1225.000s ]             ├──────────────────────────────────────────────┤                     * windows_integration (0.15.4, typescript)-3351986333
[  760.000s ]             ├───────────────────────────┤                                        * linux_integration (0.14.11, typescript)-3351986333
```

**Comment by DanielMSchmidt** [comment]
Retriggering a third time

**Comment by jsteinich** [comment]
The problems with running tests in parallel come down to race conditions accessing shared package caches (maven, nuget, etc). Some showed up relatively often, but others were rare.

**Pull request closed without merging**
