### PR TITLE
chore: remove depreciation warning for `fs.rmdir`

### PR DESCRIPTION
**Pull request by rirze**
I believe this is a Node16 depreciation message:
``` shell
(node:22795) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)

```

I encountered it today when `cdktf` deleted an old stack that was unused. It performed fine, but threw out this error.

### CODE REVIEW

**Review by DanielMSchmidt — COMMENTED** [review]
Thanks for your help! Looks like a great fix for the warning. One problem with it is that we currently support node 10 and rmSync was only added in node 12. This means we either increase the node version requirement or add a fallback in case rmSync is not defined

**Review by ansgarm — APPROVED** [review]
Thank you, @rirze!
I just checked and we already require Node v12 (we even have [this check](https://github.com/hashicorp/terraform-cdk/blob/c4222503c4571b4b368fea8c4921ed1d5ab8b899/packages/cdktf-cli/bin/cmds/helper/check-environment.ts#L55)).
I created https://github.com/hashicorp/terraform-cdk/pull/1466 to fix the parts which @DanielMSchmidt mentioned.

**Comment by ansgarm** [comment]
(fyi @rirze: I just force pushed to your branch and prepended `chore: ` to your commit message to satisfy our commit linter)

**Review by DanielMSchmidt — APPROVED** [review]

**Comment by rirze** [comment]
awesome, thanks for taking care of that for me!

**Comment by ansgarm** [comment]
No, thank _you_ for fixing this, @rirze 😄

**Pull request merged**
