### PR TITLE
chore: Update Go to version 1.18 on windows workflows

### PR DESCRIPTION
**Pull request by mutahhir**
Follow up of: https://github.com/hashicorp/terraform-cdk/pull/2214

Upgrades the version of Go in the windows platform integration tests.

### CODE REVIEW

**Review by ansgarm — APPROVED** [review]
👍

(Do you know whether our users also need Go `>=1.18` now?)

**Comment by mutahhir** [comment]
> Do you know whether our users also need Go `>=1.18` now?

If they're using Go 1.16, they'll have to upgrade, but I worry about setting it as a minimum version as a patch release. Should we do that as part of version 0.14 release?

**Comment by ansgarm** [comment]
Yeah, sounds like an 0.14 change 👍
Do you still know which change required that? A JSII upgrade?

**Comment by mutahhir** [comment]
No, I'm unsure what caused it. Wasn't an upgrade because all PRs were experiencing this.

**Pull request merged**
