### PR TITLE
feat(lib): Add nullable field to terraform variables

### LINKED ISSUE #1432: Unrecognized key: `nullable` in variable
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CDKTF Version: 0.8.3
Node.js Version: v17.3.0
Terraform Version: 1.1.2

### Affected Resource(s)

Variables

### Debug Output

https://gist.github.com/Xavientois/0153c97ea55ac1087013e1fb2a54cf91

### Expected Behavior
It should expect the optional `nullable` field in terraform variables ([source](https://www.terraform.io/language/values/variables#disallowing-null-input-values))

### Actual Behavior

It gets an `Internal Error`

### Steps to Reproduce

- Include the following in your source .tf file:
```tf
variable "gcp_project" {
  type  = string
  description = "Project id for GCP project to which the dployment will be made"
  nullable = false
}
```
- Run `cdktf convert`

### PR DESCRIPTION
**Pull request by Xavientois**
Fixes #1432

Adds the `nullable` field to `TerraformVariable` in order to handle usage of the field in HCL files from Terraform v1.1.0 and later.

### CODE REVIEW

**Review by jsteinich — CHANGES_REQUESTED** [review]
Thanks @Xavientois.

Looks good, but there is an updated snapshot needed. `yarn test` should generate it.

**Review by jsteinich — APPROVED** [review]

**Comment by Xavientois** [comment]
The failing C# tests seem to be unrelated to my changes. Is there a way to re-run the tests?

**Comment by jsteinich** [comment]
> The failing C# tests seem to be unrelated to my changes. Is there a way to re-run the tests?

That's a [known issue](https://github.com/hashicorp/terraform-cdk/issues/1410). Re-running the tests won't change anything.

**Comment by DanielMSchmidt** [comment]
Merging with admin since the only change merged since the CI run started was a docs one

**Pull request merged**
