### PR TITLE
fix(provider-generator): remove .html suffix for doc links

### PR DESCRIPTION
**Pull request by Tucker-Eric**
Terraform registry docs show 404 for docs with a `.html` suffix, this removes `.html` suffix from `linkToDocs`.

Doc links in comments before: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object.html#bucket
Doc links in comments after: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object#bucket

### CODE REVIEW

**Review by jsteinich — DISMISSED** [review]
Thanks for the update.

There are a bunch of snapshots which change with this. They can be updated by running `yarn test -u`

**Comment by Tucker-Eric** [comment]
@jsteinich , updated!

**Comment by Tucker-Eric** [comment]
> 

`yarn test:update` seems to have done the trick. It looks like the 2 failing tests are version mismatches and not snapshot issues.

**Review by DanielMSchmidt — APPROVED** [review]
Awesome, thanks a ton 👍 🎉

**Pull request merged**
