### PR TITLE
fix(lib): Fixing path for terraformhclmodule asset approach

### PR DESCRIPTION
**Pull request by javier-caylent**

### CODE REVIEW

**Comment by jsteinich** [comment]
@javier-caylent Thank you for taking the time to really dig into the issue and come up with a fix. I think it makes sense to hold off on merging this until either #947 or #948 is merged as they would result in some updates being needed.

For additional context, conceptually it shouldn't matter whether a local module is referenced absolutely or relatively; however, Terraform internally parses them differently. See https://github.com/hashicorp/terraform/blob/e09b831f6ee35d37b11b8dcccd3a6d6f6db5e5ff/internal/addrs/module_source.go#L51

**Comment by ansgarm** [comment]
@jsteinich do you know what we need to do to get this merged?

**Comment by skorfmann** [comment]
Seems like this was addressed in https://github.com/hashicorp/terraform-cdk/pull/1476 - can you confirm @jsteinich ? Close?

**Comment by jsteinich** [comment]
> Seems like this was addressed in #1476 - can you confirm @jsteinich ? Close?

Yep.

**Pull request closed without merging**
