### PR TITLE
fix(lib): fix source path generated for local modules

### LINKED ISSUE #946: Incorrect module source path generated for local modules
I believe that the source path that is generated in cdk.tf.json is incorrect for local modules, it doesn't take into account the output folder structure being `stack/<stack name>` and it needs to back up one more folder. I believe the issue is on L34
https://github.com/hashicorp/terraform-cdk/blob/337acff6cc8d01575b4e7a1974b8d796e7031206/packages/cdktf/lib/terraform-module.ts#L33-L35

It should be
```
this.source = path.join("../..", options.source);
```

**This is how I reproduce it:**

1. create project folder and cd into it.
2. run `cdktf init --template="python-pip" --local`
3. create a tf module at `modules/module1` 
4. add `modules/module1/main.tf`
```
resource "aws_s3_bucket" "bucket" {
  bucket = "cdktf-test-bucket"
  acl    = "private"
  force_destroy = true
}
```
your file structure should look like this
```
<project folder>
  |-->modules
  |       |-->module1
  |         |- main.tf
  |- cdktf.json
  |- main.py
```
5. add module reference to cdktf.json
```
"terraformModules": [
    {
      "name": "module1",
      "source": "./modules/module1"
    }
  ],  
 ```
6. run `cdktf get`
7. update stack to use module
```
#!/usr/bin/env python

from cdktf import App, TerraformStack
from constructs import Construct

from imports.aws import AwsProvider

from imports.module1 import Module1


class MyStack(TerraformStack):

    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns)

        AwsProvider(self, 'Aws', region="us-east-1")

       Module1(
           self,
           "cdktf_test_bucket",
       )

app = App()

stack = MyStack(app, "cdktf_test_stack")
app.synth()
```
8. run `cdktf diff`

you should get errors similar to
```
2021-09-02T22:50:45.536] [ERROR] default -
│ Error: Unreadable module directory
│
│ Unable to evaluate directory symlink: CreateFile ..\modules: The system
│ cannot find the file specified.


│ Error: Failed to read module directory
│
│ Module directory  does not exist or cannot be read.
```

### PR DESCRIPTION
**Pull request by JonCubed**
This fixes issue #946

### CODE REVIEW

**Comment by jsteinich** [comment]
@JonCubed Very much appreciate the fix; however, at least longer term I think that local modules need to be treated like an asset (see #648). The reason being is so that they work when using Terraform Cloud.
Since we haven't actually gotten to putting that in place yet, it may still make sense to use this in the short term though.

**Comment by JonCubed** [comment]
@jsteinich what is proposed for Assets was what I initial thought would happen with modules, so looks good to me long term. Short term I would appreciate if this could be accepted as use local modules is currently broken.

**Comment by javiortizmol** [comment]
> @jsteinich what is proposed for Assets was what I initial thought would happen with modules, so looks good to me long term. Short term I would appreciate if this could be accepted as use local modules is currently broken.

Agree with you @JonCubed, I tested the TerraformAsset option and it didn't work @jsteinich because in the cdk.tf.json file, the synt command is puting an absolute path instead of a relative path and also you can't set a relative path on the TerraformAsset, it should be absolute.
```

        tfEc2Module = TerraformAsset(self, "MyEc2Module",
            path = "/Users/javierortiz/Documents/MyGitHub/tf-cdk/modules/compute"
        )
        my_ec2 = TerraformHclModule(self, "My-ec2", 
            source = tfEc2Module.path,
            variables = {
                "ami": Locals.get("ami").get(config.environment),
                "instance_type": Locals.get("instance_type").get(config.environment),
                "vpc_security_group_ids": Locals.get("vpc_security_group_ids").get(config.environment),
                "subnet_id": Locals.get("vpc").get("public_subnets_ids").get(config.environment),
                "key_name": Locals.get("key_name").get(config.environment),
                "additional_tags": { "Name": f"python-{getWorkspace()}" }                
            }
        )

```
```
╷
│ Error: Module not found
│ 
│ The module address "assets/MyEc2Module" could not be resolved.
│ 
│ If you intended this as a path relative to the current module, use "./assets/MyEc2Module" instead. The
│ "./" prefix indicates that the address is a relative filesystem path.
```
I reviewed the cdk.tf.json file generated and I found `"source": "assets/MyEc2Module"` this is an absolute path, it is the reason behind of the error message.

I modified the cdk.tf.json file manually, changing it for `"source": "./assets/MyEc2Module"`, then on the `cdktf.out/stacks/myStack` folder I ran the `terraform init` command and works.

None of the solutions you mention work @jsteinich, why don't you just accept the solution from @JonCubed ?

**Comment by jsteinich** [comment]
> None of the solutions you mention work @jsteinich, why don't you just accept the solution from @JonCubed ?

I'm not sure the exact order of operations, but @DanielMSchmidt also started a PR for doing the "longer term" solution. Given the asset relative directory complications, I certainly agree with merging this approach. If the other PR finishes in time for the next release, great, but if not then the situation is still improved.

@JonCubed apologizes for not responding sooner. I don't have the ability to merge, but I can certainly poke the rest of the team.

**Comment by JonCubed** [comment]
no worries @jsteinich , I've worked around it by patching my local and docker image. 

I've played around with this some more and one thing that might make this fix undesirable is that it only works for the default outputs i.e. cdktf.out/stacks/<stack name>. In order to make it work for any output folder structure we would need to get the value from the output flag or cdktf.json to determine how far back we need to go. I wasn't sure how I could get this value and if this is a deal breaker or not for the short term.

**Comment by DanielMSchmidt** [comment]
@JonCubed Could you rebase this?

**Comment by JonCubed** [comment]
@DanielMSchmidt rebased

**Comment by JonCubed** [comment]
@jsteinich @DanielMSchmidt I've rebased this again. Any chance we can merge this or co-ordinate so that this can be merged?

**Review by DanielMSchmidt — APPROVED** [review]

**Comment by JonCubed** [comment]
@DanielMSchmidt thank you

**Pull request merged**
