### PR TITLE
fix: Support Auto Updating Snapshots for forks

### PR DESCRIPTION
**Pull request by jsteinich**
The goal is to support the `ci/update-snapshots` for PRs originating in forks.
I'm not certain if this will work as is and I'm not sure the best way to test this without merging in.

### CODE REVIEW

**Comment by ansgarm** [comment]
Me neither 😁 I'd be happy with just trying – we can always revert 👍

**Review by ansgarm — APPROVED** [review]

**Comment by ansgarm** [comment]
@jsteinich you could try this on a new PR of yours now :)

**Comment by jsteinich** [comment]
It took almost 2.5 hours, but it seems like it worked.

**Comment by ansgarm** [comment]
Yeah, they run in sequence because else they could overwrite each other (with git not properly detecting changes)

**Pull request merged**
