### PR TITLE
feat(lib): update attributes['//'] instead of assigning to it

### PR DESCRIPTION
**Pull request by rirze**
Should allow end users to also write to the `"//"` attribute in Terraform resources. Currently, `cdktf` overwrites this attribute with the metadata values.

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
That's an interesting use-case, what do you plan to use the // field for?

**Comment by rirze** [comment]
Personally, I'm using to test out an Pulumi-style `import` behavior. Essentially, I would attach an `importId` parameter into the `//` attribute, then run a script that generates `terraform import ...` statements based on the type of resource and the `importId` given. 

Without this, I don't any side-effect free way to 'tag' Terraform resources so I can identify which resources to import just by looking at the generated `cdktf.json` alone. 

Hopefully that gives you some context-- I have no intention to alter the existing metadata that `cdktf` attaches. If you're collecting that data, maybe I can restrict the library to only set the `//.metadata` attribute?

**Review by DanielMSchmidt — APPROVED** [review]

**Comment by DanielMSchmidt** [comment]
Could you run `yarn format` to make CI pass?

**Comment by rirze** [comment]
Sure, I'll make sure to run `yarn format`. 

I was thinking, as a way to expand this idea; should I implement a `addComment` function to `TerraformResource` (and probably `TerraformStack` too...)? Currently I'm using overrides to add this "comment" to a resource, but it results in this top level list of "overrides" in the `cdktf.json`. I'm trying to figure out if a more native solution would be ok. 

Let me know your thoughts.

**Comment by jsteinich** [comment]
> I was thinking, as a way to expand this idea; should I implement a `addComment` function to `TerraformResource` (and probably `TerraformStack` too...)

I don't think `addComment` makes sense as the json output isn't meant to be read by a human. Perhaps `addMetadata` would be a better name.



> Personally, I'm using this to test out a Pulumi-style `import` behavior. Essentially, I would attach an `importId` parameter into the `//` attribute, then run a script that generates `terraform import ...` statements based on the type of resource and the `importId` given.

This sounds like something could be built into cdktf. Probably not in the context of this PR, but possibly as part of https://github.com/hashicorp/terraform-cdk/issues/1134.

**Comment by ansgarm** [comment]
Seconding in on `addComment`:

We already have support for `Annotations` (used for example in the last code block in the [Aspects docs](https://www.terraform.io/cdktf/concepts/aspects#define-aspects)). Those `Annotations` serve the purpose of adding a comment to a construct. They are printed when running `synth` and (in the case of `error`) can even fail the synth process.

While `addMetadata` would certainly be a better name, I am a bit hesitant to just add that functionality without having done a bit more research on what kinds of workflows this is supposed to enable.

As Jon said, the import behavior would certainly be something that should be included as a first class citizen in the CDKTF with a clear and straight forward API.

---

> Currently I'm using overrides to add this "comment" to a resource, but it results in this top level list of "overrides" in the cdktf.json.

I think we could exclude all overrides nested in `//` to get rid of this to help with that.

To make the way of interacting with the overrides for `//` more beautiful to work with, you could build yourself a helper with an API similar to `Annotations.of()` or `Aspects.of()`. Something like this (untested):

```ts
class Imports {
  protected constructor(private target: TerraformResource) {}

  public static of(target: TerraformResource) {
    return new Imports(target);
  }

  public addSomeConfig(config: any): this {
    this.target.addOverride("//.__imports_config", config);
    return this;
  }
}

Imports.of(myS3Bucket).addSomeConfig({ todoo: 'put something here' })
```

**Comment by rirze** [comment]
All those who were interested in my approach on how I was automating importing resources, I wrote a detailed comment @ https://github.com/hashicorp/terraform-cdk/issues/1134#issuecomment-1035246790. 

I can provide more details as needed and I'd be comfortable moving the discussion regarding that to another issue/PR if necessary.

**Pull request merged**
