### PR TITLE
C# support continuation

### PR DESCRIPTION
**Pull request by jsteinich**
Helping out with #458. We can either merge this into that branch or just rebase and merge immediately after that is merged.

### CODE REVIEW

**Comment by jsteinich** [comment]
@anubhavmishra are you able to set up publishing to nuget.org or should we plan for starting with GitHub packages?

**Comment by skorfmann** [comment]
> @anubhavmishra are you able to set up publishing to nuget.org or should we plan for starting with GitHub packages?

Let's start with Github for now, we'll do a proper setup after the holidays.

**Comment by jsteinich** [comment]
I was hoping to avoid adding a NuGet.config file, but it seems like I may have to in order to get the tests working on all platforms. See https://github.com/NuGet/Home/issues/5127

**Comment by jsteinich** [comment]
> Provider "hashicorp/aws" v2.0.0 is not compatible with Terraform 0.13.4.

Guess we need to update our defaults.

**Comment by jsteinich** [comment]
> > Provider "hashicorp/aws" v2.0.0 is not compatible with Terraform 0.13.4.
> 
> Guess we need to update our defaults.

Or the example was just over constraining the version

**Comment by jsteinich** [comment]
Started working on publishing support [here](https://github.com/aws/jsii-release/pull/18). We can copy the script if needed sooner.

**Comment by jsteinich** [comment]
Ran into a blocking issue with using the azure provider: https://github.com/aws/jsii/issues/2367.
I don't think it will be too difficult to fix upstream, but it may take awhile to get released.

Some possible workarounds;

- We could try renaming the class, but that's a breaking change (though very few providers use attributes names `proxy`).
- We could look into switching to inner/nested types. That's a bigger and certainly breaking change, but could be nice, though I'm not 100% sure it will fix the issue)

Personally I'd rather get this merged even with azure broken, though probably don't want to announce C# support until it is addressed.

**Comment by skorfmann** [comment]
> * We could look into switching to inner/nested types. That's a bigger and certainly breaking change, but could be nice, though I'm not 100% sure it will fix the issue)

Not sure what you mean by that, could you elaborate?

> Personally I'd rather get this merged even with azure broken, though probably don't want to announce C# support until it is addressed.

Certainly something we should consider.

**Comment by jsteinich** [comment]
> > * We could look into switching to inner/nested types. That's a bigger and certainly breaking change, but could be nice, though I'm not 100% sure it will fix the issue)
> 
> Not sure what you mean by that, could you elaborate?

It would involve taking all structs/classes (block types) of a resource type and making those inner/nested types of the main resource type. For example, `KinesisFirehoseDeliveryStreamExtendedS3ConfigurationDataFormatConversionConfiguration` would become `KinesisFirehoseDeliveryStream.ExtendedS3Configuration.DataFormatConversionConfiguration`.

**Comment by jsteinich** [comment]
@skorfmann should be good to go now. The azure example integration will fail, but I'm anticipating a jsii release in the next week or so which will fix it.

Not certain how we want to handle #458. Some options:

1. Just merge this one and close that (commits should be contained here as well).
2. Merge that one, then rebase this one and merge.
3. Merge this into @pmRz00's branch, then just merge #458

**Comment by skorfmann** [comment]
> @skorfmann should be good to go now. The azure example integration will fail, but I'm anticipating a jsii release in the next week or so which will fix it.

Cool - last release of jsii is still 8th of December. Let's check with the jsii team when they're planning to do the next release.

> 
> Not certain how we want to handle #458. Some options:

> 3. Merge this into @pmRz00's branch, then just merge #458

Let's try the 3rd option. Not entirely sure how that will work, given that both PRs are based on forks. But we'll figure it out :)

**Comment by skorfmann** [comment]
Looks like a new release of jsii is imminent (today or tomorrow)

**Comment by jsteinich** [comment]
> Let's try the 3rd option. Not entirely sure how that will work, given that both PRs are based on forks. But we'll figure it out :)

I opened https://github.com/pmRz00/terraform-cdk/pull/2 since that seems like the easiest way to pull that off

**Comment by skorfmann** [comment]
> Looks like a new release of jsii is imminent (today or tomorrow)

Just checked again, no new release yet. I'll follow up early next week if nothing has been released by then.

**Comment by skorfmann** [comment]
> > Looks like a new release of jsii is imminent (today or tomorrow)
> 
> Just checked again, no new release yet. I'll follow up early next week if nothing has been released by then.

@jsteinich The new jsii release woul include aws/jsii#2367 - and that's what we're waiting for, correct?

**Comment by jsteinich** [comment]
> @jsteinich The new jsii release woul include [aws/jsii#2367](https://github.com/aws/jsii/issues/2367) - and that's what we're waiting for, correct?

Yep. We could also remove the Azure example if didn't want to merge failing tests.

**Comment by skorfmann** [comment]
> > @jsteinich The new jsii release woul include [aws/jsii#2367](https://github.com/aws/jsii/issues/2367) - and that's what we're waiting for, correct?
> 
> Yep. We could also remove the Azure example if didn't want to merge failing tests.

Yes, let's wait until tomorrow. If there's still no release, I'd disable the example and merge anyway.

**Comment by skorfmann** [comment]
[jsii 1.17.0](https://github.com/aws/jsii/releases/tag/v1.17.0) just got released (huge thanks to the jsii team for cutting this release /cc @RomainMuller).

**Comment by skorfmann** [comment]
Looks like there are multiple versions of jsii in the project?

**Comment by jsteinich** [comment]
> Looks like there are multiple versions of jsii in the project?

I'm pretty sure jsii-srcmak references the other version. I'll try to find time tonight to either find a workaround or make a PR to update it.

**Comment by skorfmann** [comment]
@jsteinich FYI: There's an open question about a change to the snapshots https://github.com/aws/jsii-srcmak/pull/293#discussion_r557228900 - I don't have enough context to answer.

**Comment by skorfmann** [comment]
Continuing in #477

**Pull request merged**
