### PR TITLE
fix(tests): enable windows test with escapes

### LINKED ISSUE #810: Re-enable Snapshot test for windows
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This snapshot test is currently disabled: https://github.com/hashicorp/terraform-cdk/blob/50476e97feed31990cb84f69242a49586ad650d6/test/typescript/multiple-stacks/test.ts#L62-L64
We should update the snapshot on a windows machine and re-enable it.

### PR DESCRIPTION
**Pull request by jsteinich**
Fixes #810

### CODE REVIEW

**Comment by jsteinich** [comment]
`error TS2304: Cannot find name 'onWindows'`. I'm not really sure why it isn't finding the defined constant. I didn't have that issue locally.

**Comment by ansgarm** [comment]
@jsteinich
I think that was moved to some test utility quite recently because it was re-used in another test case as well.
https://github.com/hashicorp/terraform-cdk/blob/main/test/test-helper.ts#L212

**Review by ansgarm — APPROVED** [review]

**Comment by jsteinich** [comment]
Thanks @ansgarm. Found it and now the specific test is passing. Just failing the terraform cloud test now.

**Comment by ansgarm** [comment]
> Just failing the terraform cloud test now.

Ah, well. We had some weird trouble with that one recently.

**Comment by jsteinich** [comment]
Seems like we might have some new flakiness with our tests, but the latest run did pass everything.

**Pull request merged**
