### PR TITLE
fix(provider-generator): Fix false block attributes

### LINKED ISSUE #1403: CloudFront argument lost during synth
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

* nodejs 12.22.7
* python 3.10.0
* cdktf 0.8.1
* cdktf-cdktf-provider-aws 3.0.1

### Affected Resource(s)

`CloudfrontDistributionDefaultCacheBehaviorForwardedValues` has the problem

I find it interesting that `CloudfrontDistributionOrderedCacheBehaviorForwardedValues` does not have the problem, despite having a similar method signature, e.g. both have `query_string` as an argument.

### Debug Output

Here's a repo that reproduce the problem:

https://github.com/cmclaughlin/cdktf-cloudfront-query-string-bug

Running `cdktf deploy` generates this Terraform error:

```
╷
│ Error: Missing required argument
│
│   on cdk.tf.json line 54, in resource.aws_cloudfront_distribution.cloudfronttest_distro_CAF0A17E.default_cache_behavior.forwarded_values:
│   54:           }
│
│ The argument "query_string" is required, but no definition was found.
╵
```

However, changing `query_string` on line 48 of `main.py` to True will get the plan to pass (but that's not the desired value)

### Expected Behavior

Plan cleanly w/ `query_string=False`

### Actual Behavior

Terraform `Missing required argument` error

### Steps to Reproduce

* Clone https://github.com/cmclaughlin/cdktf-cloudfront-query-string-bug
* Setup a python virtualenv, install requirements, etc
* Run `cdktf deploy`

### Important Factoids

We recently upgraded from cdktf 0.3 to 0.7.0. We didn't get very far with 0.7.0 before seeing more breaking changes in 0.8.0, so we upgraded to 0.8.1.

I haven't yet narrowed down when or where this problem started... but I don't think we had the problem prior to the recent upgrades.

### PR DESCRIPTION
**Pull request by jsteinich**
Fixes #1403

### CODE REVIEW

**Review by ansgarm — APPROVED** [review]

**Comment by ansgarm** [comment]
Thanks @jsteinich! Great work 🎉

**Comment by cmclaughlin** [comment]
Thanks @jsteinich!

**Comment by cmclaughlin** [comment]
@ansgarm could we get a release published with this fix?

**Comment by ansgarm** [comment]
@cmclaughlin Sure! I'll have a look at that tomorrow 👍

**Pull request merged**
