### PR TITLE
chore(release): Pre-releases should use next version

### PR DESCRIPTION
**Pull request by jsteinich**
This takes care of the main part of #561. Also includes some tools to help with #656.

Using [standard-version](https://github.com/conventional-changelog/standard-version) to handle bumping the version number in a manner similar to semantic-release but without the release.

Can run `yarn prepare-release` or `yarn prepare-release --release-as minor` when preparing for an actual release to bump the version and generate the changelog.

Follow up:
We also discussed changing the qualifier. For at least Java that would probably be a good idea; however, there isn't an easy way to change for just 1 language. Probably makes sense to hold off on any changes until we get actual user feedback requesting changes.

### CODE REVIEW

**Comment by skorfmann** [comment]
Awesome, thanks! So, this would work like this when merging the PR?

| Target | current release version | pre-release | 
|--------|-----------------|---------------------|
| [NPM](https://www.npmjs.com/package/cdktf)    | 0.7.0           | 0.8.0-pre.500       |
| [pypi](https://pypi.org/project/cdktf/0.1.0/#history)   | 0.7.0           | 0.8.0.dev500      |
| [nuget](https://www.nuget.org/packages/HashiCorp.Cdktf)  | 0.7.0           | 0.8.0-pre.500 |
| [maven](https://search.maven.org/artifact/com.hashicorp/cdktf)  | 0.7.0           | 0.8.0-pre.500 |

**Comment by jsteinich** [comment]
> this would work like this when merging the PR?

Yep.
It increments the pre-release version each time rather than using the github build number, so technically it will start with `0.8.0-pre.0`, but we should have a tag to be able to track the exact commit if needed.

**Comment by jsteinich** [comment]
I've been doing some testing here: https://github.com/jsteinich/standard-version-test

I think that I've run into https://github.com/conventional-changelog/standard-version/issues/724 as everything worked for the 1st pre-release, but failed on the next one.

**Comment by jsteinich** [comment]
I did some more investigation and managed to get things working.

I'm not going to update the release instructions quite yet since the release changelog generation hasn't been fully tested yet. I figure we can try it out with the next release and compare to the existing script. Since that is a secondary goal, if it doesn't work we can just not use it and continue iterating or remove.

**Comment by skorfmann** [comment]
Seems to work as expected:

```
✗ yarn prepare-next-release
yarn run v1.22.5
$ standard-version --prerelease pre --release-as minor --skip.changelog=true --skip.commit=true
✔ bumping version in package.json from 0.7.0 to 0.8.0-pre.1
✔ bumping version in packages/cdktf-cli/package.json from 0.0.0 to 0.8.0-pre.1
✔ bumping version in packages/cdktf/package.json from 0.0.0 to 0.8.0-pre.1
✔ bumping version in packages/@cdktf/hcl2cdk/package.json from 0.0.0 to 0.8.0-pre.1
✔ bumping version in packages/@cdktf/hcl2json/package.json from 0.0.0 to 0.8.0-pre.1
✔ bumping version in packages/@cdktf/provider-generator/package.json from 0.0.0 to 0.8.0-pre.1
✔ tagging release v0.8.0-pre.1
ℹ Run `git push --follow-tags origin pr/jsteinich/1257 && npm publish --tag pre` to publish
```

Is there anything else missing or would you consider this as good to go @jsteinich ?

**Comment by jsteinich** [comment]
> Is there anything else missing or would you consider this as good to go

@skorfmann I think it is good to go.

**Pull request merged**
